services:
  jaeger:
    # v1.45
    image: "quay.io/jaegertracing/all-in-one@sha256:5d5c9d2d8c8cbb42f1db4aac1f1f8487bac63da6802004d0da8580fc0c7311a1"
    environment:
      SPAN_STORAGE_TYPE: "elasticsearch"
      ES_SERVER_URLS: "http://elasticsearch:9200"
      COLLECTOR_OTLP_ENABLED: true
    ports:
      # healthcheck admin
      - "127.0.0.1:14271:14271/udp"
      # healthcheck collector
      - "127.0.0.1:14269:14269"
      # gRPC for oltp traces
      - "127.0.0.1:4317:4317"
      # healthcheck ingester
      - "127.0.0.1:14270:14270"
      # ui
      - "127.0.0.1:16686:16686"
    restart: "on-failure"

    deploy:
      resources:
        limits:
          memory: '1G'
    depends_on:
      - "elasticsearch"
  elasticsearch:
    # v7.17.10
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.10"
    restart: "on-failure"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
    volumes:
      - type: "bind"
        source: "elasticsearch"
        target: "/usr/share/elasticsearch/data"
    deploy:
      resources:
        limits:
          memory: '2G'
        reservations:
          memory: '2G'
  prometheus:
    # v2.44.0
    image: "quay.io/prometheus/prometheus@sha256:0f0b7feb6f02620df7d493ad7437b6ee95b6d16d8d18799f3607124e501444b1"
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - "./prometheus:/etc/prometheus:ro"
      - type: "bind"
        source: "prometheus"
        target: "/prometheus"
    restart: "on-failure"
    deploy:
      resources:
        limits:
          memory: '1G'
  mongodb:
    image: "registry.hub.docker.com/mongodb/mongodb-community-server:6.0.4-ubi8-20230524T062919Z"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '8G'
        reservations:
          cpus: '2'
          memory: '8G'
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - type: "bind"
        source: "mongodb"
        target: "/data/db"
  ycsb-squared:
    image: "ycsb-squared"
    build:
      context: "."
      dockerfile: "./Dockerfile"
    depends_on:
      - "jaeger"
      - "prometheus"
      - "mongodb"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '3G'
        reservations:
          cpus: '1'
          memory: '3G'

volumes:
  mongodb:
  prometheus:
  elasticsearch: